### ISSUE TITLE
Spelling Errors result in incorrect predictions

### ISSUE THREAD

**Issue by BGebken** [BGebken/Linnaeus-Classifier#21]
It appears that some spelling issues are causing problems:
![image](https://user-images.githubusercontent.com/35474536/56804036-6540c180-67f2-11e9-842c-3dcec45bc773.png)

I am not sure if it is possible to make the model more robust so that it can avoid spelling issues triggering the wrong result

**Comment by nelabdiel** [comment]
Hi @BGebken this is due to the fact that the model never saw such edge cases. The model is analyzing clusters of words and since that combination is highly unlikely (100% of the words misspelled) the model does not know how to handle it. We would have to do cost effective analysis to decide whether we should factor in edge cases like that one or not.

**Comment by BGebken** [comment]
@nelabdiel Lets discuss tomorrow. I just ran a couple test cases and it looks like I might be doing something wrong:

![image](https://user-images.githubusercontent.com/35474536/56871536-625df080-69ed-11e9-860e-1a3f4328c402.png)

It looks like the first word of the string is triggering the wrong classification. Bilateral Tinnitus should be a fairly easy match to "hearing loss". So I think I set something up wrong

**Comment by nelabdiel** [comment]
You may have to pull again. I haven't updated the model but it seems like you may have a previous version because I just tried bilateral tinnitus and got hearing loss. I tried all of those and an acceptable answer with all of the above.


(I've created a web interface for myself)
<img width="325" alt="Screen Shot 2019-04-29 at 11 42 54 AM" src="https://user-images.githubusercontent.com/15022766/56908304-0d18f200-6a74-11e9-90dd-95a31892113d.png">

**Comment by BGebken** [comment]
Got the new files, thanks!
